# Generated by Django 3.2.9 on 2021-12-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('img_url', models.CharField(max_length=200)),
                ('start_work_hour', models.IntegerField()),
                ('end_work_hour', models.IntegerField()),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
