# Generated by Django 3.2.9 on 2021-12-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museums',
            name='end_work_hour',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='museums',
            name='start_work_hour',
            field=models.CharField(max_length=10),
        ),
    ]
