# Generated by Django 3.2.9 on 2021-12-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0002_auto_20211220_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museums',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
