# Generated by Django 3.2.9 on 2021-12-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0003_alter_museums_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='museums',
            name='category',
            field=models.IntegerField(null=True),
        ),
    ]
