# Generated by Django 3.2.9 on 2021-12-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0004_museums_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museums',
            name='phone_number',
            field=models.CharField(max_length=80),
        ),
    ]
