# Generated by Django 3.2.9 on 2022-01-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0005_alter_museums_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museums',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
